"""Emit the reproducibility appendix pieces straight from code/config so the
paper cannot drift from the implementation again.

    python -m geobench.appendix > results/unified/tables/appendix_repro.tex
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

from .config import (BAD_PHRASES, BAD_WORDS, DEFAULT_K, PPL_MODEL, RANKERS, REPO_ROOT)
from .prompts import SYSTEM_PROMPT, USER_TEMPLATE


def tex_escape(s: str) -> str:
    return s.replace("&", r"\&").replace("%", r"\%").replace("#", r"\#").replace("_", r"\_")


def stealthrank_hparams():
    out = {}
    for p in sorted((REPO_ROOT / "branches/Stealth-Rank/configs").glob("suffix_llama-3.1-8b_*.yaml")):
        c = yaml.safe_load(p.read_text())["parameters"]
        out[p.stem.replace("suffix_llama-3.1-8b_", "")] = {k: c[k].get("value", c[k].get("values")) for k in
                                                         ("num_iter", "lr", "topk", "length", "batch_size", "ngram", "target", "temperature", "noise_stds", "iter_steps") if k in c}
    return out


def raf_hparams():
    txt = (REPO_ROOT / "branches/RAF/pipeline.py").read_text()
    flags = re.findall(r'"--(\w+)",\s*"([^"]+)"', txt)
    return dict(flags)


def sts_hparams():
    txt = (REPO_ROOT / "branches/STS/rank_opt.py").read_text()
    m = {k: re.search(rf"{k}\s*=\s*(\d+)", txt) for k in ("batch_size", "top_k", "num_samples")}
    slurm = (REPO_ROOT / "branches/STS/slurm_executable_files/run_sts_cseo.slurm").read_text()
    n = re.search(r"--num_iter (\d+)", slurm)
    return {"num_iter": n.group(1) if n else "?", **{k: (v.group(1) if v else "?") for k, v in m.items()}}


def main():
    print("% ---- auto-generated by geobench/appendix.py ----")
    print(r"\paragraph{Ranking prompt.}")
    print(r"\begin{quote}\small\texttt{" + tex_escape(SYSTEM_PROMPT) + r"}\end{quote}")
    print(r"\begin{quote}\small\texttt{" + tex_escape(USER_TEMPLATE.replace("\n", " ")) + r"}\end{quote}")
    print(rf"Ranks are the median over $K={DEFAULT_K}$ seeded random product orderings; greedy decoding.")
    print(r"\paragraph{Rankers.} " + ", ".join(f"{k} (\\texttt{{{tex_escape(v[1])}}})" for k, v in RANKERS.items()) + ".")
    print(rf"\paragraph{{Perplexity reference model.}} \texttt{{{tex_escape(PPL_MODEL)}}}, fp16, ratio of PPL(adv)/PPL(orig).")
    print(r"\paragraph{Keyword lexicon $W_{\text{bad}}$ (24 words).} " + ", ".join(sorted(BAD_WORDS)) + ".")
    print(r"\paragraph{Phrase lexicon (54 phrases).} " + ", ".join(tex_escape(p) for p in sorted(BAD_PHRASES)) + ".")
    print(r"Matching: lowercase, strip punctuation except \#, phrase = substring match, word = whole-token match.")
    try:
        print(r"\paragraph{StealthRank.} " + tex_escape(str(stealthrank_hparams())))
        print(r"\paragraph{RAF.} " + tex_escape(str(raf_hparams())))
        print(r"\paragraph{STS.} " + tex_escape(str(sts_hparams())))
    except Exception as e:
        print(f"% branch configs not found: {e!r}")


if __name__ == "__main__":
    main()
