_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.11.13
            "5": 0.19.6
            "6": 4.56.2
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 5
catalog:
    value: coffee_machines
comment:
    value: main experiment
dataset:
    value: json
fluency:
    value: 1
iter_steps:
    value:
        - 0
        - 50
        - 200
        - 500
        - 1500
length:
    value: 30
lr:
    value: 0.03
mode:
    value: suffix
model:
    value: mistral-7b
ngram:
    value: 5
noise_stds:
    value:
        - 0.1
        - 0.05
        - 0.01
        - 0.005
        - 0.001
num_iter:
    value: 2000
precision:
    value: 16
random_inference:
    value: true
random_order:
    value: true
result_dir:
    value: result/suffix/v1
seed:
    value: 42
similarity:
    value: 1
target:
    value: 50
target_product_idx:
    value: 8
temperature:
    value: 0.1
test_iter:
    value: 100
topk:
    value: 10
